# Numpy

In [0]:
import numpy as np

In [7]:
x=np.array([1,2,3])
print(x)

[1 2 3]


In [8]:
type(x)

numpy.ndarray

## converting list to array

In [0]:
lis=[1,2,3]
x=np.asarray(lis)


In [10]:
print(type(x))

<class 'numpy.ndarray'>


In [11]:
lis=[4,5,6]
x=np.asarray(lis,float)
print(x)

[4. 5. 6.]


## shape of array

In [12]:
x.shape

(3,)

In [13]:
np.shape(x)

(3,)

In [14]:
x=np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [15]:
x.shape

(2, 3)

## indexing

In [16]:
x[0,0]

1

In [17]:
x[0,0:2]

array([1, 2])

In [18]:
x[0,:]

array([1, 2, 3])

## Arrays of zeros

In [19]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Identity matrix

In [0]:
x=np.eye(4,4)

In [23]:
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## array of normally distributed random numbers betweeen 0 and 1 

In [0]:
x=np.random.random((4,5))                 # normally distributed between 0 and 1

In [25]:
print(x)

[[0.80641173 0.44986954 0.21200965 0.08622818 0.0042898 ]
 [0.78595722 0.22698122 0.59719226 0.38048673 0.51065472]
 [0.97072175 0.38375467 0.07988278 0.94777498 0.60190165]
 [0.73058435 0.96068411 0.76633909 0.08551491 0.69367049]]


## transpose of array

In [0]:
z=x.T

In [29]:
print(z)

[[0.64219898 0.48704235 0.40394745 0.47833912]
 [0.8313756  0.27947616 0.41160918 0.50386386]
 [0.75772485 0.06461279 0.79789137 0.90397668]
 [0.92681937 0.62335043 0.67826068 0.17545202]
 [0.37101043 0.8206383  0.99305634 0.80884042]]


## reshaping array

In [0]:
y=x.reshape(20,1)

In [31]:
print(y)

[[0.64219898]
 [0.8313756 ]
 [0.75772485]
 [0.92681937]
 [0.37101043]
 [0.48704235]
 [0.27947616]
 [0.06461279]
 [0.62335043]
 [0.8206383 ]
 [0.40394745]
 [0.41160918]
 [0.79789137]
 [0.67826068]
 [0.99305634]
 [0.47833912]
 [0.50386386]
 [0.90397668]
 [0.17545202]
 [0.80884042]]


## createing array with range of elements

In [32]:
a=np.arange(5)
print(a)

[0 1 2 3 4]


In [0]:
b=np.arange(5)

In [35]:
c=a+b
d=a-b
e=a*b
print(c,d,e)

[0 2 4 6 8] [0 0 0 0 0] [ 0  1  4  9 16]


## all scalar operation will be broadcasted

In [36]:
a=np.random.random((2,3))
print(a)
print(a+1)               # adding a scalar

[[0.81717708 0.31894282 0.27017524]
 [0.39438566 0.48405631 0.07067884]]
[[1.81717708 1.31894282 1.27017524]
 [1.39438566 1.48405631 1.07067884]]


## converting floor(integer) of random array

In [38]:
a=np.floor(np.random.random((2,3))*10)
print(a)

[[8. 2. 6.]
 [2. 6. 7.]]


## inner and outer product

In [40]:
u=[1,2,3]
v=[-1,0,1]
pl=np.inner(u,v)             # inner product   multiply each element of vector and ading them
print(pl)

2


In [41]:
p2=np.outer(u,v)             # outer product   multiply each values of one vector to every values of other vector
print(p2)                                

[[-1  0  1]
 [-2  0  2]
 [-3  0  3]]


## dot product

In [44]:
a=np.ones((2,3))
b=np.ones((3,2))
np.dot(a,b)

array([[3., 3.],
       [3., 3.]])

In [45]:
np.dot(b.T,a.T)

array([[3., 3.],
       [3., 3.]])

## sum of numbers in each columns and each row

In [0]:
a=np.ones((2,3))

In [47]:
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [48]:
np.sum(a,axis=0)                      #column sum

array([2., 2., 2.])

In [49]:
np.sum(a,axis=1)                      #row sum

array([3., 3.])